import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useRouter } from 'next/router';
import Link from 'next/link';


export default function Home() {
  const router = useRouter();  
  
  function goToDetailPage() {
    router.push({
      pathname: '/posts/[postId]',
      query: {
        postId: 2,
        ref: 'Second'
      }
    })
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Juffy learn NextJS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>

          <div> 
            <h1>Post List Page </h1>
            <ul>
                <li><Link href="/posts">Get All Page 🔗</Link></li>
                <li><Link href="/posts/create">Create a Page 🔗</Link></li>
                <li>Dynamic routes
                    <ul>
                        <li><Link href="/posts/1">Get a Post by a parameter 🔗</Link></li>
                        <li><Link href="/posts/123/abc/xyz">Get a sub-page through multiple parameter 🔗</Link></li>
                    </ul>
                </li>
                <li><button onClick={goToDetailPage}>Go to detail page id=2</button></li>
                
            </ul>
          </div>

        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
